language: objective-c  #1 Don't change this to 'Swift'.
script:
    - xcodebuild clean test -project "Barcode Scanner.xcodeproj" -scheme "Barcode Scanner" -destination "platform=iOS Simulator,name=iPhone X,OS=11.4" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
osx_image: xcode10 #2
#xcode_project: Barcode Scanner.xcodeproj #3
#xcode_scheme: Barcode Scanner #4
#xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X
